### ISSUE TITLE
IP address does not show up in the table

### ISSUE THREAD

**Issue by devhoussam1998** [mohammadhprp/filament-ip-to-country-flag-column#1]
<img width="1212" alt="Screenshot 2023-08-09 at 13 38 44" src="https://github.com/mohammadhprp/filament-ip-to-country-flag-column/assets/121255432/71f827cc-3277-427b-a424-a5ac129b9ede">

**Comment by mohammadhprp** [comment]
Hi @devhoussam1998,

I believe the reason the IP address doesn't show up is that the user's IP is null.
In the package, if the IP is null, it returns the `‍‍‍‍default` value. If you haven't set the default value, it's going to return `-`.
