### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by MedanWeb** [mohammadhprp/filament-ip-to-country-flag-column#3]
It seems that for some reason the request to receive the flag is not working. Most likely, in the `ip2Location` method, `CURLOPT_URL => 'https://iplocation.com/'` does not return data and blocks the request, so the page on which `IPToCountryFlagColumn` is located returns a 524 response code. 
![изображение](https://github.com/mohammadhprp/filament-ip-to-country-flag-column/assets/27902209/b8aec50a-b166-4f07-a942-9452ad4ea4d7)

**Comment by mohammadhprp** [comment]
Hi @amfetaminf2017,

Thanks for reporting the timeout issue. I've tested `ip2Location` and it seems to be working now. The issue might have been a temporary server problem.
